// Protocol Forge: 45-Workday Plan data
// Monday June 1, 2026 through Friday July 31, 2026

window.PLAN = {
  title: "Protocol Forge",
  subtitle: "45-Workday Plan to Become a Deep Smart Contract Engineer",
  range: "Mon June 1, 2026 — Fri July 31, 2026",
  mission:
    "I can derive protocol mechanisms, implement them in Solidity, attack them, optimize them, audit them, onboard quickly to unfamiliar codebases, and produce work a real DeFi team would respect.",

  // Final evidence standard — the July 31 scorecard
  evidence: [
    "Six protocol modules implemented",
    "Ten mathematical notebooks",
    "At least 200 meaningful unit tests",
    "At least 20 fuzz tests",
    "At least 12 stateful invariants",
    "At least five exploit proofs",
    "At least two fork tests against real protocol integrations",
    "At least two measured gas optimizations",
    "Five audit-style security documents",
    "Three public technical write-ups",
    "One recorded architecture walkthrough",
    "One external protocol review or open-source contribution",
    "Ten targeted conversations with engineers, auditors or founders",
    "Upgradeable proxy + ERC-4337 account + bridge implemented and attacked",
    "Slither, Aderyn and Echidna/Medusa run with triaged findings",
    "One protocol deployed and verified on a public testnet, owned by a Safe multisig",
    "A live, wallet-connected full-stack dApp anyone can use",
    "A Web3 developer portfolio site marketing the work",
    "Entered one audit contest (Code4rena/Sherlock/CodeHawks) or bug bounty",
  ],

  weeks: [
    {
      n: 1,
      title: "EVM Fundamentals, Fixed-Point Math & Vault Attacks",
      range: "June 1–5",
      summary:
        "Stop treating Solidity like ordinary application code. By Friday you should have built and exploited a vault.",
      gate: "You are ready to continue only when you can derive share conversion math and explain exactly how rounding enabled theft.",
      days: [
        {
          date: "Mon, June 1",
          title: "Blockchain Foundations, EVM Mental Model & Foundry",
          learn: [
            "Blockchain fundamentals: blocks, hashing, proof-of-work vs proof-of-stake, consensus, finality",
            "Where Ethereum sits: L1 vs L2/rollups, nodes, the mempool, how a transaction gets included",
            "Ethereum accounts, transactions, gas, calldata, storage and logs",
            "How Solidity functions compile into EVM execution",
            "msg.sender, msg.value, reverts, custom errors and events",
            "Difference between memory, calldata and storage",
            "Why contract state must be treated as permanent financial state",
          ],
          do: [
            "Create the protocol-forge repository",
            "Install Foundry and initialize the workspace",
            "Set up packages, test, notebooks, docs, audits folders",
            "Implement Counter.sol, SimpleBank.sol, MockERC20.sol",
            "Implement a feature-complete ERC-20 (mint, burn, cap, EIP-2612 permit)",
            "Write tests for deposits, withdrawals, unauthorized actions, reverts",
            "Add GitHub Actions to run forge test on every push",
          ],
          artifact: [
            "Working repository",
            "Twenty basic Foundry tests",
            "docs/BLOCKCHAIN_FOUNDATIONS.md (consensus, finality, L1 vs L2) + docs/EVM_EXECUTION_MODEL.md",
            "2-min oral: how Ethereum reaches consensus, and why Solidity is not a normal backend API",
          ],
        },
        {
          date: "Tue, June 2",
          title: "Safe Token Transfers, Storage & Adversarial State",
          learn: [
            "ERC-20 balances and allowances",
            "External calls and return values",
            "Reentrancy at a conceptual level",
            "Checks-effects-interactions",
            "How one state mutation affects all later users",
          ],
          do: [
            "Implement SafeTransferLab.sol",
            "Write a deliberately unsafe withdrawal function",
            "Write a reentrant attacker contract",
            "Demonstrate the attack in a test",
            "Repair the withdrawal path",
            "Write attacker-vs-fixed comparison test",
          ],
          artifact: [
            "First exploit proof",
            "audits/REENTRANCY_MINI_REPORT.md",
            "Ten new attack-focused tests",
            "Oral: what state was inconsistent during the external call",
          ],
        },
        {
          date: "Wed, June 3",
          title: "WAD, RAY, Rounding & Full-Precision Arithmetic",
          learn: [
            "Why Solidity has no native float for protocol accounting",
            "WAD: values scaled by 1e18",
            "RAY: values scaled by 1e27",
            "Round-down vs round-up behavior",
            "Why different actors need different rounding directions",
            "Full-precision mulDiv reasoning",
          ],
          do: [
            "Build notebooks/01_fixed_point_math.ipynb",
            "Calculate interest accrual, share conversion, normalization, drift",
            "Implement mulWadDown/Up, divWadDown/Up, mulDivDown/Up",
            "Fuzz each Solidity function against the Python reference model",
          ],
          artifact: [
            "packages/math-kernel/FixedPointMath.sol",
            "Fifty differential tests",
            "docs/MATH.md fixed-point section",
            "Oral: three rounding examples by hand",
          ],
        },
        {
          date: "Thu, June 4",
          title: "ERC-4626 Vault Share Mathematics",
          learn: [
            "How a vault represents deposits through shares",
            "Relationship between total assets, total shares, each claim",
            "Why attacker first-deposit + donation rounds victim to zero shares",
          ],
          do: [
            "Build notebooks/02_erc4626_inflation_attack.ipynb",
            "Simulate empty vault, attacker deposit, donation, victim deposit",
            "Show victim receiving zero shares, attacker redeeming value",
            "Implement VulnerableVault.sol",
            "Implement the exact inflation-attack test",
          ],
          artifact: [
            "Working ERC-4626 inflation exploit",
            "Notebook: attack profit under different donation sizes",
            "Failing property test demonstrating the vulnerable condition",
            "Oral: why did the victim receive zero shares",
          ],
        },
        {
          date: "Fri, June 5",
          title: "Secure Vault Design & First Audit Report",
          learn: [
            "Virtual shares and virtual assets",
            "Initial-liquidity protections",
            "Minimum-share defenses",
            "The limits of every mitigation",
            "How to communicate a vulnerability clearly",
          ],
          do: [
            "Implement ProtectedVault.sol",
            "Tests showing the prior attack no longer succeeds profitably",
            "Fuzz: tiny deposits, donations, repeated deposits, sequences",
            "Write your first full security report",
          ],
          artifact: [
            "packages/vaults/VulnerableVault.sol + ProtectedVault.sol",
            "audits/ERC4626_INFLATION_REPORT.md",
            "At least 75 cumulative tests",
            "5-min recorded explanation of attack and mitigation",
          ],
        },
      ],
    },
    {
      n: 2,
      title: "AMMs, Flash Loans & Oracle Manipulation",
      range: "June 8–12",
      summary:
        "Turn market mathematics into a security problem. Implement a constant-product AMM, distort its spot price with a flash loan, then break a lending-style valuation that trusts it.",
      gate: "You must be able to calculate whether a flash-loan oracle attack is profitable before running the code.",
      days: [
        {
          date: "Mon, June 8",
          title: "Constant-Product AMM Derivation",
          learn: [
            "Derive x * y = k",
            "Token output after a swap",
            "Fee-adjusted swap output",
            "Pool spot price and slippage",
            "How a large trade changes the price",
            "Why liquidity depth controls manipulation cost",
          ],
          do: [
            "Build notebooks/03_constant_product_amm.ipynb",
            "Simulate swaps for different reserve sizes",
            "Plot price impact as trade size increases",
            "Write the equations in docs/MATH.md",
          ],
          artifact: [
            "Complete AMM reference notebook",
            "Written derivation of swap output",
            "Oral: solve one swap by hand",
          ],
        },
        {
          date: "Tue, June 9",
          title: "Build a Constant-Product AMM",
          learn: [
            "Liquidity provision and LP share accounting",
            "Reserve updates",
            "Swap fees",
            "Minimum-liquidity edge cases",
            "Invariant preservation",
          ],
          do: [
            "Implement ConstantProductAMM.sol",
            "Add/remove liquidity, swap A->B, swap B->A",
            "Unit and fuzz tests verifying reserves and fee behavior",
            "Invariant: swaps cannot reduce fee-adjusted product incorrectly",
          ],
          artifact: [
            "Working AMM",
            "Twenty-five AMM tests",
            "First AMM invariant test",
          ],
        },
        {
          date: "Wed, June 10",
          title: "Flash Loans & Atomic Capital",
          learn: [
            "Atomic execution",
            "Borrow, use and repay within one transaction",
            "Flash-loan fees",
            "Why flash loans are not inherently malicious",
            "Why they amplify weak oracle or accounting designs",
          ],
          do: [
            "Implement FlashVault.sol + flash borrower interface",
            "Tests: successful repayment, failed repayment revert, fee, arbitrage",
            "Invariant: lender balance after >= starting balance + fee",
          ],
          artifact: [
            "Flash-loan module",
            "Flash-loan invariant test",
            "3-min explanation of atomic borrowing",
          ],
        },
        {
          date: "Thu, June 11",
          title: "Build a Spot-Price Oracle Exploit",
          learn: [
            "Why an AMM reserve ratio is a manipulable spot price",
            "Attack-cost vs borrowed-value reasoning",
            "How flash liquidity makes temporary manipulation practical",
            "Why composability creates cross-contract attack surfaces",
          ],
          do: [
            "Implement VulnerableSpotOracle.sol",
            "Minimal collateral-borrowing contract trusting AMM spot price",
            "Flash borrow -> distort price -> inflate collateral -> over-borrow -> repay -> profit",
            "Python: attack profitability vs liquidity depth",
          ],
          artifact: [
            "Second major exploit proof",
            "notebooks/04_oracle_manipulation.ipynb",
            "Attack-profit graph",
            "audits/ORACLE_MANIPULATION_REPORT.md draft",
          ],
        },
        {
          date: "Fri, June 12",
          title: "Secure Oracle Adapter, TWAP, Randomness & Fork Testing",
          learn: [
            "External price feeds and feed decimals",
            "Timestamp freshness, heartbeats, stale data",
            "TWAP vs instantaneous price",
            "On-chain randomness: why block-variable RNG is exploitable, commit-reveal, Chainlink VRF",
            "Fork testing against deployed contract state",
          ],
          do: [
            "Implement OracleAdapter.sol, normalize decimals to WAD",
            "Reject stale prices",
            "Replace vulnerable spot-price borrowing calculation",
            "Build a weak-RNG lottery, exploit it, then fix it with Chainlink VRF or commit-reveal",
            "Replay yesterday's attack against the secure version",
            "Write one fork test using a pinned feed + fixed block",
          ],
          artifact: [
            "Secured oracle integration",
            "Failed exploit against fixed design",
            "Weak-RNG exploit + VRF/commit-reveal fix",
            "First fork test",
            "Completed audits/ORACLE_MANIPULATION_REPORT.md",
            "5-min oral: spot price, TWAP, secure randomness, external oracle tradeoffs",
          ],
        },
      ],
    },
    {
      n: 3,
      title: "Uniswap v3 Math, StableSwap & Low-Level Precision",
      range: "June 15–19",
      summary:
        "Study square-root pricing, liquidity ranges and stablecoin-specific AMM mathematics. The plan gets mathematically ambitious here.",
      gate: "You must be able to explain how integer encoding, liquidity ranges and iterative numerical solutions affect protocol correctness.",
      days: [
        {
          date: "Mon, June 15",
          title: "Square-Root Pricing & Q64.96",
          learn: [
            "Fixed-point binary representation",
            "Why Uniswap v3 uses square-root price",
            "What sqrtPriceX96 represents",
            "Conversion between human price and encoded price",
            "Precision-loss risks",
          ],
          do: [
            "Build notebooks/05_uniswap_v3_math.ipynb",
            "Convert prices to sqrt-encoded values and back",
            "Implement SqrtPriceMathLab.sol",
            "Differential tests against Python",
          ],
          artifact: [
            "Q64.96 conversion library",
            "Twenty precision tests",
            "Oral: explain sqrtPriceX96 without notes",
          ],
        },
        {
          date: "Tue, June 16",
          title: "Ticks & Concentrated Liquidity Positions",
          learn: [
            "Price ranges and ticks",
            "In-range vs out-of-range positions",
            "Why liquidity becomes one token outside its range",
            "Capital efficiency vs risk",
          ],
          do: [
            "Extend the Uniswap v3 notebook",
            "Model full-range, tight-range, wide-range LP positions",
            "Simulate token composition as price moves",
            "Implement simplified liquidity amount calculations in Solidity",
          ],
          artifact: [
            "Position-value simulation",
            "Solidity liquidity math lab",
            "docs/MATH.md concentrated-liquidity section",
          ],
        },
        {
          date: "Wed, June 17",
          title: "StableSwap Mathematics",
          learn: [
            "Why stable-to-stable pools want low slippage near parity",
            "Constant-sum vs constant-product behavior",
            "Role of an amplification parameter",
            "Iterative numerical solutions",
            "Why stable AMMs become dangerous under depeg",
          ],
          do: [
            "Build notebooks/06_stableswap_math.ipynb",
            "Compare constant product, constant sum, simplified StableSwap",
            "Plot slippage near parity and during depeg",
            "Write numerical-solver pseudocode before Solidity",
          ],
          artifact: [
            "StableSwap notebook",
            "Written explanation of amplification and depeg risk",
            "Hand-derived examples",
          ],
        },
        {
          date: "Thu, June 18",
          title: "Implement a Simplified Stablecoin AMM",
          learn: [
            "Iterative convergence in contract code",
            "Precision and gas tradeoffs",
            "Convergence failure",
            "Parameter selection risk",
          ],
          do: [
            "Implement StableSwapLab.sol (two stable assets, deposits, swaps, amp)",
            "Fuzz against the Python model",
            "Tests: near-parity, severe imbalance, depeg, precision loss",
          ],
          artifact: [
            "Simplified StableSwap implementation",
            "Differential tests",
            "Documented limitations (educational, not production)",
          ],
        },
        {
          date: "Fri, June 19",
          title: "Gas Measurement & First Yul Exposure",
          learn: [
            "Gas reports",
            "Storage reads and writes",
            "Calldata optimization",
            "Custom errors",
            "Checked vs unchecked arithmetic",
            "Inline assembly and Yul risks",
          ],
          do: [
            "Measure gas for critical math and swap paths",
            "Optimize one pure-math function safely",
            "Re-implement one narrow function in Yul",
            "Prove output equivalence via fuzz testing",
            "Reject any optimization that makes correctness unclear",
          ],
          artifact: [
            "docs/GAS_OPTIMIZATION.md initial version",
            "Before-and-after gas measurements",
            "One equivalence-tested Yul function",
            "Oral: lower gas is useless if the proof surface becomes unsafe",
          ],
        },
      ],
    },
    {
      n: 4,
      title: "Isolated Lending Market Core",
      range: "June 22–26",
      summary:
        "Maps directly onto generalized lending work: isolated markets from a factory, ERC-4626 capital routing, optimized architecture.",
      gate: "You should now be able to design, implement and explain the core of an isolated lending protocol from scratch.",
      days: [
        {
          date: "Mon, June 22",
          title: "Lending Architecture & Market Isolation",
          learn: [
            "Supply assets vs collateral assets",
            "Isolated market risk",
            "Factory deployment patterns",
            "Tokenized claims vs internal balance accounting",
            "Why external yield vault integration adds efficiency and risk",
          ],
          do: [
            "Design the lending architecture before coding",
            "Write market actors, trusted assumptions, asset-flow, failure modes",
            "Implement LendingMarketFactory.sol, IsolatedLendingMarket.sol skeleton, config structs",
          ],
          artifact: [
            "docs/LENDING_ARCHITECTURE.md",
            "Market factory skeleton",
            "Unit tests for deployment and configuration",
          ],
        },
        {
          date: "Tue, June 23",
          title: "Supply Shares, Borrow Shares & Interest Indices",
          learn: [
            "Why protocols use shares and indices vs per-block updates",
            "Utilization, borrow APR, supply APR, reserve factor",
            "Discrete interest accrual",
            "Index-based user debt accounting",
          ],
          do: [
            "Build notebooks/07_lending_interest_liquidations.ipynb",
            "Simulate utilization 0-100%, kinked curves, debt growth, earnings",
            "Implement InterestRateModel.sol, supply/borrow share accounting, index updates",
          ],
          artifact: [
            "Interest-rate notebook",
            "Working index-based accrual",
            "Tests for time travel, repayment, supplier accounting",
          ],
        },
        {
          date: "Wed, June 24",
          title: "Collateral, Health Factor & Oracle Integration",
          learn: [
            "Collateral valuation",
            "Loan-to-value",
            "Liquidation threshold",
            "Health factor",
            "Decimals and unit normalization",
            "Oracle-driven solvency",
          ],
          do: [
            "Implement collateral deposit/withdraw, borrow, repay, health factor",
            "Integrate your secure oracle adapter",
            "Tests preventing excess borrow, unsafe withdrawal, stale-price borrow, decimal mismatch",
          ],
          artifact: [
            "Usable isolated lending market",
            "Health-factor tests",
            "docs/MATH.md lending section",
          ],
        },
        {
          date: "Thu, June 25",
          title: "Liquidations, Bonuses & Bad Debt",
          learn: [
            "Liquidation eligibility",
            "Partial liquidation",
            "Liquidator bonus and close factor",
            "Bad debt",
            "Liquidator profitability",
            "Why overly generous bonuses are dangerous",
          ],
          do: [
            "Implement LiquidationEngine.sol",
            "Simulate normal liquidation, sharp crash, insufficient collateral, bad debt, bonus variations",
            "Property tests: healthy cannot be liquidated, insolvent can, no excess transfer",
          ],
          artifact: [
            "Complete liquidation flow",
            "Bad-debt scenarios in Python and Solidity",
            "Written risk analysis",
          ],
        },
        {
          date: "Fri, June 26",
          title: "Attack the Lending Market",
          learn: [
            "Lending-specific threat modeling",
            "Oracle manipulation",
            "Share inflation",
            "Borrow cap failures",
            "Liquidation edge cases",
            "External-vault integration risk",
          ],
          do: [
            "Attempt manipulated spot price, stale feed, tiny-value rounding, donation, withdrawal edges",
            "Foundry invariant handlers for deposit, borrow, repay, withdraw, liquidate",
            "Repair discovered weaknesses",
          ],
          artifact: [
            "First full protocol security pass",
            "audits/LENDING_AUDIT_REPORT.md draft",
            "At least four lending invariants",
            "5-min architecture walkthrough",
          ],
        },
      ],
    },
    {
      n: 5,
      title: "Stablecoin Infrastructure & Peg Risk",
      range: "June 29 – July 3",
      summary:
        "Build an overcollateralized stablecoin engine plus a simplified Peg Stability Module, then examine failure under depeg and liquidation stress.",
      gate: "You must be able to explain why 'fully backed' does not automatically mean 'safe under liquidation, liquidity and oracle stress.'",
      days: [
        {
          date: "Mon, June 29",
          title: "Overcollateralized Stablecoin Design",
          learn: [
            "Stablecoin liabilities",
            "Collateralized debt positions",
            "Minting against collateral",
            "Minimum collateral ratios, debt ceilings, stability fees",
            "Protocol solvency",
          ],
          do: [
            "Design ForgeUSD",
            "Formal accounting: what backs each unit, when minting occurs, what creates insolvency",
            "Implement ForgeUSD.sol, CDPEngine.sol skeleton, collateral deposit + mint",
          ],
          artifact: [
            "Stablecoin architecture note",
            "Initial minting tests",
            "Core solvency invariant draft",
          ],
        },
        {
          date: "Tue, June 30",
          title: "Stablecoin Liquidations & Debt Accounting",
          learn: [
            "Stablecoin debt shares",
            "Liquidation penalties",
            "Auction vs immediate liquidation simplification",
            "Surplus and deficit accounting",
            "Collateral volatility",
          ],
          do: [
            "Implement burn, repay, withdraw collateral, liquidate",
            "Reuse the secure oracle module",
            "Model collateral crashes in Python",
            "Invariants: outstanding backed under assumptions, no withdrawal into insolvency",
          ],
          artifact: [
            "Functional collateralized stablecoin engine",
            "Liquidation tests",
            "Bad-debt simulation",
          ],
        },
        {
          date: "Wed, July 1",
          title: "Peg Stability Module",
          learn: [
            "Why a collateralized stablecoin drifts from target",
            "Fixed-price mint/redeem modules",
            "Stable collateral exposure",
            "Capacity limits and fee spreads",
            "Why peg defense introduces concentrated collateral risk",
          ],
          do: [
            "Study the Maker-style PSM mechanism",
            "Implement PegStabilityModule.sol",
            "Approved deposit, fixed-price mint with fee, redeem, capacity limits",
            "Exact-accounting tests",
          ],
          artifact: [
            "Working PSM module",
            "PSM accounting notebook section",
            "Peg support vs collateral concentration risk write-up",
          ],
        },
        {
          date: "Thu, July 2",
          title: "Depeg Scenarios & Failure Analysis",
          learn: [
            "Collateral depeg risk",
            "Liquidity shortfall",
            "Redemption rushes",
            "Oracle lag",
            "PSM capacity exhaustion",
            "Insolvency despite nominal overcollateralization",
          ],
          do: [
            "Build notebooks/08_stablecoin_depeg_scenarios.ipynb",
            "Simulate collateral to $0.98, $0.90, oracle delay, mass redemption, ceiling failure",
            "Reproduce one bad configuration in Solidity tests",
            "Add configuration guards",
          ],
          artifact: [
            "Depeg-risk simulation",
            "Exploit or failure proof",
            "Mitigated design",
          ],
        },
        {
          date: "Fri, July 3",
          title: "Stablecoin Audit & Cross-Protocol Integration",
          learn: [
            "Composability risk",
            "Stablecoin as lending collateral",
            "Stablecoin pools under stress",
            "Cascading liquidation behavior",
          ],
          do: [
            "Allow ForgeUSD into one controlled integration (AMM asset or borrowable)",
            "Model a depeg affecting the integrated system",
            "Write audits/STABLECOIN_RISK_REPORT.md",
            "Client-style changelog: scope, assumptions, coverage, remaining risks",
          ],
          artifact: [
            "Stablecoin module integrated into your lab",
            "Full stablecoin risk report",
            "5-min recorded defense",
          ],
        },
      ],
    },
    {
      n: 6,
      title: "Perpetual Exchange Math & Margin Engines",
      range: "July 6–10",
      summary:
        "The most ambitious new component. Not a full exchange: enough core accounting to demonstrate leveraged positions, funding, liquidations and incentive attacks.",
      gate: "You must be able to explain the complete path from collateral deposit to open position, funding accrual, liquidation and bad debt.",
      days: [
        {
          date: "Mon, July 6",
          title: "Position, Collateral, Leverage & PnL Math",
          learn: [
            "Long vs short positions",
            "Position notional",
            "Collateral and leverage",
            "Entry price and mark price",
            "Unrealized profit and loss",
            "Maintenance margin",
          ],
          do: [
            "Build notebooks/09_perpetual_funding_liquidations.ipynb",
            "Calculate long PnL, short PnL, margin ratio, liquidation price",
            "Write protocol specifications before coding",
          ],
          artifact: [
            "Perpetual-accounting notebook foundation",
            "Written formulas and examples",
            "Oral: calculate a liquidation price by hand",
          ],
        },
        {
          date: "Tue, July 7",
          title: "Build a Minimal Margin Engine",
          learn: [
            "Collateral custody",
            "Position opening",
            "Increasing and decreasing positions",
            "Realized vs unrealized PnL",
            "Solvency when profitable users withdraw",
          ],
          do: [
            "Implement MarginEngine.sol: deposit, open long, open short, close, current margin",
            "Use your secure oracle for index price",
            "Tests across price movements",
          ],
          artifact: [
            "Minimal perpetual margin engine",
            "Profit-and-loss unit tests",
            "Solvency accounting notes",
          ],
        },
        {
          date: "Wed, July 8",
          title: "Funding Rates & Open-Interest Imbalance",
          learn: [
            "Why perp prices need pressure toward spot",
            "Funding payments",
            "Long vs short open interest",
            "Cumulative funding indices",
            "Time-based accounting",
            "How funding can be gamed",
          ],
          do: [
            "Implement FundingRateModel.sol",
            "Track long OI, short OI, funding accumulation, per-position funding owed",
            "Model one-sided market flow in Python",
            "Attempt a strategy that exploits poor funding updates",
          ],
          artifact: [
            "Funding module",
            "Funding-game simulation",
            "First perp-specific attack hypothesis",
          ],
        },
        {
          date: "Thu, July 9",
          title: "Perpetual Liquidations & Insurance Funds",
          learn: [
            "Maintenance margin",
            "Liquidation fees",
            "Keeper incentives",
            "Bad debt and insurance funds",
            "Cascading liquidation scenarios",
            "Oracle and execution latency risks",
          ],
          do: [
            "Implement LiquidationModule.sol, InsuranceFund.sol",
            "Simulate rapid up vs shorts, rapid down vs longs, underfunded insurance, stale oracle",
            "Liquidation and insolvency tests",
          ],
          artifact: [
            "Liquidatable position flow",
            "Insurance-fund accounting",
            "Adversarial stress scenarios",
          ],
        },
        {
          date: "Fri, July 10",
          title: "Perp Attack Review & Risk Report",
          learn: [
            "Funding manipulation",
            "Oracle manipulation",
            "Position-size caps",
            "Open-interest imbalance limits",
            "Liquidation keeper incentives",
            "Parameter-risk documentation",
          ],
          do: [
            "Construct funding-update gaming, stale-oracle liquidation, oversized position attacks",
            "Write fixes or protective configuration",
            "Produce audits/PERPS_RISK_REPORT.md",
            "Compare your engine conceptually against documented GMX threat surface",
          ],
          artifact: [
            "Working educational perp engine",
            "Three adversarial tests",
            "Complete risk report",
            "7-min recorded explanation",
          ],
        },
      ],
    },
    {
      n: 7,
      title: "Prediction Markets, Conditional Tokens & Signed Settlement",
      range: "July 13–17",
      summary:
        "Targets prediction-market mechanisms publicly documented by Polymarket: conditional tokens, complete-set collateralization, signed-order settlement.",
      gate: "You must understand why outcome token accounting, oracle resolution and signed exchange settlement are separate security surfaces.",
      days: [
        {
          date: "Mon, July 13",
          title: "Binary Outcome Collateral Mathematics",
          learn: [
            "Binary outcomes",
            "Complete-set collateralization",
            "Yes and No token relationships",
            "Why one Yes+No set corresponds to one collateral unit",
            "ERC-1155 vs ERC-20 representations",
          ],
          do: [
            "Build notebooks/10_prediction_market_collateral.ipynb",
            "Derive split, merge, winner redemption accounting",
            "Implement ConditionalTokensLab.sol",
            "Support collateral split into Yes and No tokens",
          ],
          artifact: [
            "Conditional-token contract",
            "Collateral-conservation tests",
            "Oral: why Yes+No together are always redeemable before settlement",
          ],
        },
        {
          date: "Tue, July 14",
          title: "Merge, Redeem & Resolution Oracles",
          learn: [
            "Condition preparation",
            "Resolution and redemption",
            "Invalid resolution",
            "Oracle trust",
            "Dispute or governance assumptions",
          ],
          do: [
            "Implement merge complete sets, resolve condition, redeem winning positions",
            "Tests: correct outcome, incorrect redemption, double redemption, invalid oracle actor, conservation",
          ],
          artifact: [
            "Working binary settlement engine",
            "Prediction-market invariant suite",
            "Resolution-risk documentation",
          ],
        },
        {
          date: "Wed, July 15",
          title: "Signed Orders & Onchain Settlement",
          learn: [
            "Limit orders",
            "Makers and takers",
            "EIP-712 typed signatures",
            "Nonces and replay protection",
            "Expiration",
            "Atomic settlement",
          ],
          do: [
            "Implement SignedOrderExchange.sol",
            "Signed sell order, signature verification, nonce tracking, expiration, atomic settlement",
            "Replay and expired-order attack tests",
          ],
          artifact: [
            "Minimal signed-order exchange",
            "Replay-protection tests",
            "Written settlement-flow diagram",
          ],
        },
        {
          date: "Thu, July 16",
          title: "Prediction-Market Security Attacks",
          learn: [
            "Resolution manipulation",
            "Broken collateral conservation",
            "Signature replay",
            "Fee asymmetry",
            "Invalid token IDs",
            "Settlement front-running considerations",
          ],
          do: [
            "Attack tests: unauthorized resolution, replay, incorrect merge, double redemption, mispriced fee",
            "Invariants: locked collateral = outstanding sets, redemption <= locked, nonces prevent replay",
          ],
          artifact: [
            "Prediction-market exploit suite",
            "Security section for the module",
            "Invariant tests",
          ],
        },
        {
          date: "Fri, July 17",
          title: "Polymarket-Style Mechanism Review",
          learn: [
            "Hybrid exchange architecture",
            "Offchain matching vs onchain settlement",
            "Exchange trust assumptions",
            "Conditional-token audit surfaces",
            "Why speed and correctness compete",
          ],
          do: [
            "Read Polymarket CTF Exchange V2 architecture",
            "Compare against your educational implementation",
            "Write what you implemented, what production adds, what you omitted, where it fails at scale",
            "Produce audits/PREDICTION_MARKET_RISK_REPORT.md",
          ],
          artifact: [
            "Complete prediction-market module",
            "Comparison report against real architecture",
            "5-min mechanism walkthrough",
          ],
        },
      ],
    },
    {
      n: 8,
      title:
        "Security Engineering, Invariants, EVM Optimization & Code Reading",
      range: "July 20–24",
      summary:
        "Stop adding protocol categories and attack everything you have built. Use Damn Vulnerable DeFi for targeted drills alongside your own attacks.",
      gate: "You should be able to enter an unfamiliar protocol repo, identify value flows, locate dangerous assumptions and begin writing useful tests within one day.",
      days: [
        {
          date: "Mon, July 20",
          title: "EVM Internals & Gas-Safe Yul Work",
          learn: [
            "Stack, memory, storage slots, calldata",
            "ABI encoding and function selectors",
            "Revert data",
            "SLOAD and SSTORE cost implications",
            "Yul for narrowly scoped optimization only",
          ],
          do: [
            "Inspect compiled output for selected functions",
            "Implement two Yul variants (a math op, a calldata/hashing op)",
            "Benchmark both against Solidity versions",
            "Fuzz for output equivalence; delete indefensible Yul",
          ],
          artifact: [
            "packages/evm-optimization/YulMath.sol",
            "Measured gas results",
            "Equivalence test suite",
            "Updated docs/GAS_OPTIMIZATION.md",
          ],
        },
        {
          date: "Tue, July 21",
          title: "Stateful Invariant Testing Across the Monorepo",
          learn: [
            "Handler-based invariant testing",
            "Ghost variables",
            "Bounded random actions",
            "Solvency invariants",
            "Conservation invariants",
            "False positives from invalid assumptions",
          ],
          do: [
            "Write invariant handlers for vaults, lending, stablecoin, perp, prediction market",
            "Vault assets cover claims; lending debt cannot vanish; stablecoin liabilities obey assumptions",
            "Perp withdrawals bounded; prediction redemption <= locked; flash loans end repaid + fees",
          ],
          artifact: [
            "Full invariant-test directory",
            "At least twelve invariants",
            "A log of every failure discovered",
          ],
        },
        {
          date: "Wed, July 22",
          title: "Formal Specifications & Static Analysis",
          learn: [
            "Assertions vs assumptions",
            "Property specifications",
            "Static-analysis findings",
            "Formal-checking limits",
            "Why passing tools does not equal security",
          ],
          do: [
            "Run static analysis on your contracts",
            "Use Solidity assertions for narrow mathematical properties",
            "Attempt SMTChecker verification for selected pure/accounting functions",
            "Categorize findings: real bug, false positive, design risk, accepted simplification; repair real issues",
          ],
          artifact: [
            "docs/FORMAL_PROPERTIES.md",
            "Static-analysis results",
            "Verified or attempted proof notes",
            "Bug-fix commits tied to detected findings",
          ],
        },
        {
          date: "Thu, July 23",
          title: "Exploit Gauntlet",
          learn: [
            "Review: reentrancy, share inflation, flash-loan oracle manipulation",
            "Stale prices, liquidation edge cases",
            "Funding manipulation, signature replay, accounting insolvency",
          ],
          do: [
            "Create a unified exploit test suite",
            "Each attack: run vs vulnerable (show break), run vs fixed, explain mitigation",
            "Solve at least two Damn Vulnerable DeFi challenges without copying a solution",
          ],
          artifact: [
            "test/exploits/ polished demonstration suite",
            "Eight exploit write-ups or attack notes",
            "Two external security exercise solutions",
          ],
        },
        {
          date: "Fri, July 24",
          title: "One-Day External Codebase Onboarding Simulation",
          learn: [
            "Rapidly onboarding to unfamiliar codebases while maintaining reliability",
            "Today simulates that pressure",
          ],
          do: [
            "Select one open-source DeFi codebase you have not studied",
            "Give yourself one working day",
            "Produce architecture diagram, asset-flow map, trust assumptions, key formulas, high-risk functions",
            "Five attack hypotheses + at least one runnable test/repro/improvement",
            "Report real issues responsibly; do not publicly accuse without verifying",
          ],
          artifact: [
            "audits/EXTERNAL_CODEBASE_REVIEW.md",
            "One serious codebase review under time pressure",
            "Optional legitimate issue or PR if you found a real improvement",
          ],
        },
      ],
    },
    {
      n: 9,
      title: "Production Simulation, Public Proof & Opportunity Creation",
      range: "July 27–31",
      summary:
        "Turn technical work into career signal: delivery speed, client communication, scoping, reliability, and the artifacts needed to earn trust.",
      gate: "Today is not for new content. It is for proving you own everything you built.",
      days: [
        {
          date: "Mon, July 27",
          title: "Client-Style Feature Sprint",
          learn: [
            "Requirement scoping",
            "Time estimation",
            "Acceptance criteria",
            "Backward compatibility",
            "Risk disclosure",
            "Communicating what is not included",
          ],
          do: [
            "Mock client request: add emergency controls, borrow caps, configurable oracle staleness without breaking accounting/tests",
            "Estimate the work, write acceptance criteria, implement the feature",
            "Add unit, fuzz and invariant tests; produce a concise delivery note",
          ],
          artifact: [
            "Client-style feature delivery",
            "docs/CLIENT_STYLE_CHANGELOG.md",
            "Evidence of spec-to-tested-implementation speed",
          ],
        },
        {
          date: "Tue, July 28",
          title: "Repository Hardening & Reproducibility",
          learn: [
            "Professional repository standards",
            "Reproducible builds",
            "Test organization",
            "Version pinning",
            "Coverage gaps",
            "Security disclosure and non-production disclaimers",
          ],
          do: [
            "Clean structure, pin dependencies, configure CI",
            "Run full tests, gas reporting, static analysis; fix documentation drift",
            "Add commands for build, test, invariants, exploit demos, fork tests, gas report",
          ],
          artifact: [
            "Professional-grade repository organization",
            "Clean README installation instructions",
            "Green CI",
            "Full reproducibility pass",
          ],
        },
        {
          date: "Wed, July 29",
          title: "Technical Writing Day",
          learn: [
            "Make complicated mechanisms comprehensible to engineers, auditors and founders",
          ],
          do: [
            "Building and Breaking an Isolated Lending Market (rates, health factors, liquidations, oracle attacks, invariants)",
            "From AMMs to Perpetuals (constant product, StableSwap, funding, margin and liquidation)",
            "Prediction Market Settlement from First Principles (Yes/No collateral, split/merge/redeem, signed settlement, resolution risk)",
          ],
          artifact: [
            "Three polished technical articles",
            "Diagrams and equations",
            "Public-ready repository documentation",
          ],
        },
        {
          date: "Thu, July 30",
          title: "External Review & Engineer Outreach",
          learn: [
            "How to request technical feedback",
            "How to present limitations honestly",
            "How to ask sharp questions",
            "How to turn a project into a professional relationship",
          ],
          do: [
            "Identify ten engineers, auditors, founders or contributors",
            "Short message: your repo, the most relevant module, one intelligent question, a request for one criticism",
            "Submit one legitimate external contribution or review request",
            "Record responses and action items",
          ],
          artifact: [
            "Ten targeted outreach messages",
            "At least one external feedback request attached to real code",
            "A backlog of fixes based on feedback",
          ],
        },
        {
          date: "Fri, July 31",
          title: "Final Defense & Next Opportunity Packet",
          learn: [
            "Prove you own everything you built. No-notes technical defense.",
          ],
          do: [
            "Derive ERC-4626 share math + inflation exploit; constant-product swap output + manipulation cost",
            "Explain sqrtPriceX96; StableSwap purpose + depeg risk; utilization-driven rates; health factor + liquidation profitability",
            "Explain stablecoin collateralization + PSM risk; calculate a perp liquidation; funding manipulation; prediction-market conservation",
            "Explain your twelve invariants; walk every exploit; explain gas optimizations; state every limitation honestly",
            "Finalize README, architecture video, security report index, resume bullets, target teams, 90-day continuation plan",
          ],
          artifact: [
            "Math-first body of work: vaults, AMMs, oracles, lending, stablecoins, perps, prediction markets",
            "Invariants, exploits, gas optimization, external code review",
            "Professional technical communication",
          ],
        },
      ],
    },
    {
      n: 10,
      title: "Production Patterns & Capstone",
      range: "Aug 3–7",
      summary:
        "Close the gaps the public curricula assume you know: upgradeable proxies, account abstraction, bridges, governance, MEV, weird ERC-20s, named tooling, and a real testnet deploy. This is what separates a math-strong builder from an engineer a DeFi team trusts on day one.",
      gate: "You can build, attack, and fix a proxy, an ERC-4337 account, and a bridge; run Slither, Aderyn and Echidna/Medusa; and ship a Safe-owned, verified testnet deployment.",
      days: [
        {
          date: "Mon, Aug 3",
          title: "Upgradeable Proxies & delegatecall Storage",
          learn: [
            "Transparent, UUPS and Diamond proxy patterns",
            "How delegatecall executes implementation code against proxy storage",
            "Storage layout and storage collisions",
            "Initializer vs constructor; the uninitialized-proxy risk",
            "Upgrade authorization and centralization risk",
          ],
          do: [
            "Implement a UUPS proxy + implementation with OpenZeppelin",
            "Write a storage-collision exploit against a naive upgrade",
            "Test a real upgrade preserving state",
            "Add initializer guards and an upgrade-authorization check",
          ],
          artifact: [
            "packages/upgradeable/ proxy module",
            "Storage-collision exploit proof",
            "audits/PROXY_UPGRADE_REPORT.md",
          ],
        },
        {
          date: "Tue, Aug 4",
          title: "Account Abstraction (ERC-4337 + EIP-7702)",
          learn: [
            "EntryPoint, UserOperation, bundlers and paymasters",
            "validateUserOp and the validation/execution split",
            "Signature schemes and gas sponsorship",
            "EIP-7702 vs ERC-4337 tradeoffs",
            "Why account abstraction is the hottest 2026 surface",
          ],
          do: [
            "Implement a minimal smart account (validateUserOp + execute)",
            "Implement a paymaster that sponsors gas",
            "Sign and send a UserOperation through a testnet bundler",
            "Write tests for replay, nonce and signature failures",
          ],
          artifact: [
            "packages/account-abstraction/ minimal ERC-4337 account + paymaster",
            "Working UserOperation demo",
            "Notes on the EntryPoint trust model",
          ],
        },
        {
          date: "Wed, Aug 5",
          title: "Bridges, Cross-Chain & Signature Replay",
          learn: [
            "Lock-mint vs burn-mint bridge designs",
            "Message verification and validator trust",
            "Cross-chain signature replay",
            "EIP-712 domain separation, chainId binding and nonces",
            "Bridge hack post-mortems: Ronin, Wormhole, Nomad",
          ],
          do: [
            "Implement a minimal lock/mint bridge with EIP-712 messages",
            "Build a cross-chain signature-replay exploit",
            "Fix it with chainId-bound domains and nonces",
            "Add a fork test against a pinned chain state",
          ],
          artifact: [
            "packages/bridge/ module",
            "Cross-chain replay exploit proof",
            "audits/BRIDGE_REPORT.md",
          ],
        },
        {
          date: "Thu, Aug 6",
          title: "DAO Governance, MEV & Weird ERC-20s",
          learn: [
            "OpenZeppelin Governor + Timelock",
            "Flash-loan voting attacks (Beanstalk)",
            "MEV: frontrunning, sandwich attacks, slippage, private mempools",
            "Weird ERC-20s: fee-on-transfer, rebasing, ERC-777 callbacks, missing return values",
          ],
          do: [
            "Build a Governor + Timelock governance flow",
            "Demonstrate a flash-loan governance attack and its mitigation",
            "Add slippage protection to your AMM",
            "Harden lending/AMM against fee-on-transfer and ERC-777 reentrancy",
          ],
          artifact: [
            "packages/governance/ module",
            "Governance-attack proof",
            "audits/MEV_AND_WEIRD_ERC20_NOTES.md",
          ],
        },
        {
          date: "Fri, Aug 7",
          title: "Named Tooling, Testnet Deploy & Safe",
          learn: [
            "Slither and Aderyn for static analysis",
            "Echidna and Medusa for property-based fuzzing",
            "Deploy + verify on a public testnet",
            "Safe multisig ownership and monitoring/alerting",
          ],
          do: [
            "Run Slither + Aderyn across the monorepo and triage findings",
            "Write Echidna or Medusa property tests for one protocol",
            "Deploy and verify one protocol on a public testnet",
            "Transfer ownership to a Safe multisig",
          ],
          artifact: [
            "Tooling reports (Slither, Aderyn, Echidna/Medusa)",
            "Verified testnet deployment",
            "Safe-owned contract + updated SECURITY.md / GAS_OPTIMIZATION.md",
          ],
        },
      ],
    },
    {
      n: 11,
      title: "Full-Stack dApp & Going Pro",
      range: "Aug 10–14",
      summary:
        "The deep protocol work is done. This week makes it hireable and monetizable: wire a usable frontend onto your contracts, ship a live dApp anyone can click, then open the income doors — portfolio site, audit contests, bug bounties, freelance, and job boards. The skills follow → do → monetize loop.",
      gate: "You have a live, wallet-connected dApp anyone can use, a Web3 portfolio site that markets you, and you have entered at least one audit contest or applied to five roles.",
      days: [
        {
          date: "Mon, Aug 10",
          title: "Frontend dApp Foundations",
          learn: [
            "JavaScript/TypeScript for the client layer",
            "Next.js + React for dApp UIs",
            "wagmi + viem (the modern Ethereum client stack)",
            "RainbowKit / ConnectKit wallet connection",
            "Reading contract state, sending transactions, chain switching, tx status",
          ],
          do: [
            "Scaffold a Next.js + wagmi + viem + RainbowKit app",
            "Connect MetaMask and read a value from one of your contracts",
            "Send a write transaction and surface pending/success/error states",
            "Handle wrong-network and disconnected states",
          ],
          artifact: [
            "apps/web/ dApp scaffold",
            "Wallet connect + one read + one write working against a testnet",
            "Notes on viem vs ethers.js tradeoffs",
          ],
        },
        {
          date: "Tue, Aug 11",
          title: "Flagship dApp — A Usable Product",
          learn: [
            "Translating a protocol into a product UX",
            "Token approvals and allowance flows",
            "Live balances, slippage display, and optimistic UI",
            "Empty/loading/error states for on-chain data",
          ],
          do: [
            "Wire a real UI onto your AMM or lending market on a testnet",
            "Support connect wallet, deposit, swap or borrow, and live balances",
            "Add approval handling and human-readable error messages",
            "Deploy the frontend (Vercel) pointed at the verified testnet contracts",
          ],
          artifact: [
            "A live, wallet-connected dApp anyone can use",
            "Public dApp URL + demo video",
            "Screenshots for the portfolio",
          ],
        },
        {
          date: "Wed, Aug 12",
          title: "dApp Infrastructure & an NFT Mint",
          learn: [
            "RPC providers: Alchemy / Infura",
            "The Graph: subgraphs for indexing contract events",
            "IPFS / Pinata for token + NFT metadata",
            "Etherscan verification and reading a live contract",
          ],
          do: [
            "Move the dApp onto an Alchemy/Infura RPC with a key",
            "Build a minimal subgraph indexing your protocol's events and query it from the UI",
            "Build a small ERC-721 NFT mint dApp with IPFS metadata",
            "Verify all deployed contracts on the block explorer",
          ],
          artifact: [
            "Subgraph indexing live events",
            "NFT mint dApp with IPFS metadata",
            "All contracts verified on Etherscan",
          ],
        },
        {
          date: "Thu, Aug 13",
          title: "Monetize — Portfolio, Contests, Freelance",
          learn: [
            "A Web3 developer portfolio site that markets you",
            "Audit contests: Code4rena, Sherlock, CodeHawks",
            "Bug bounties: Immunefi",
            "Freelance (Upwork) and crypto job boards (CryptoJobsList, web3.career, LinkedIn)",
          ],
          do: [
            "Build a portfolio site: live dApp, contracts, audit reports, GitHub, resume, contact",
            "Write tight resume bullets from the monorepo and the live dApp",
            "Register for Code4rena / Sherlock / CodeHawks and read one past contest report",
            "Create profiles on Immunefi, CryptoJobsList, web3.career; optimize LinkedIn for blockchain",
          ],
          artifact: [
            "Live Web3 portfolio site",
            "Resume bullets + LinkedIn updated",
            "Accounts created on at least two contest/bounty/job platforms",
          ],
        },
        {
          date: "Fri, Aug 14",
          title: "From Scratch, Then Apply",
          learn: [
            "Unguided build: your own idea, no tutorial",
            "Scoping a small but complete dApp",
            "Optional: a simple bot (arbitrage / trading / sniping) as an income avenue",
            "Turning projects into applications and first opportunities",
          ],
          do: [
            "Design and build one small dApp entirely solo, no guide, and deploy it",
            "Optional: build a basic bot against a testnet (e.g., arbitrage watcher)",
            "Enter one live audit contest OR apply to five roles / send five freelance proposals",
            "Add everything to the portfolio site",
          ],
          artifact: [
            "One from-scratch dApp deployed and in the portfolio",
            "First audit-contest entry or five applications/proposals sent",
            "A standing pipeline: contests + bounties + applications in flight",
          ],
        },
      ],
    },
  ],
};
